/* Kafka 기반 RMS Middleware — 03. 오류 시험용 기준정보 (선택)
   "05 파라미터 없음" 시험: 파라미터가 하나도 없는 레시피 (EQP_002 / MODEL / Z900 → RECIPE_NOPARAM) */
USE YsRmsDB;
GO
IF NOT EXISTS (SELECT 1 FROM dbo.TB_RMS_RECIPE WHERE RECIPE_ID = N'RECIPE_NOPARAM')
    INSERT INTO dbo.TB_RMS_RECIPE (RECIPE_ID, EQUIP_ID, FACTOR_ID, FACTOR_VALUE) VALUES (N'RECIPE_NOPARAM', N'EQP_002', N'MODEL', N'Z900');
GO
