/* RMS 결과 조회 — 인덱스 검토 (결과조회 생성.pptx p.8 "EVENT_TIME·EQUIP_ID 조회조건에 필요한 인덱스 확인")
   조회 조건: EVENT_TIME 기간(필수) + EQUIP_ID(선택), 정렬: EVENT_TIME 내림차순 */
USE YsRmsDB;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_RMS_RESULT_EVENT_TIME' AND object_id = OBJECT_ID(N'dbo.TB_RMS_RESULT'))
    CREATE INDEX IX_RMS_RESULT_EVENT_TIME ON dbo.TB_RMS_RESULT (EVENT_TIME DESC) INCLUDE (EQUIP_ID, RECIPE_ID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_RMS_RESULT_EQUIP_TIME' AND object_id = OBJECT_ID(N'dbo.TB_RMS_RESULT'))
    CREATE INDEX IX_RMS_RESULT_EQUIP_TIME ON dbo.TB_RMS_RESULT (EQUIP_ID, EVENT_TIME DESC) INCLUDE (RECIPE_ID);
GO
-- Detail은 PK(RESULT_ID, PARAMETER_ID)로 RESULT_ID 조회가 이미 빠르다
