/* ============================================================================
   RMS 기준정보 관리 — 02. 제공된 CREATE TABLE (기준정보관리 생성.pptx p.7·8 원문 그대로)
   ============================================================================ */
USE YsRmsDB;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE dbo.TB_EQUIPMENT (
  EQUIP_ID      NVARCHAR(50)  NOT NULL PRIMARY KEY,
  EQUIP_NAME    NVARCHAR(100) NOT NULL,
  USE_YN        CHAR(1)       NOT NULL DEFAULT 'Y',
  CREATED_AT    DATETIME2(3)  NOT NULL DEFAULT SYSDATETIME(),
  UPDATED_AT    DATETIME2(3)  NULL,
  CONSTRAINT CK_EQUIPMENT_USE_YN CHECK (USE_YN IN ('Y','N'))
);

CREATE TABLE dbo.TB_RMS_RECIPE (
  RECIPE_ID     NVARCHAR(50)  NOT NULL PRIMARY KEY,
  EQUIP_ID      NVARCHAR(50)  NOT NULL,
  FACTOR_ID     NVARCHAR(50)  NOT NULL,
  FACTOR_VALUE  NVARCHAR(200) NOT NULL,
  USE_YN        CHAR(1)       NOT NULL DEFAULT 'Y',
  CREATED_AT    DATETIME2(3)  NOT NULL DEFAULT SYSDATETIME(),
  UPDATED_AT    DATETIME2(3)  NULL,
  CONSTRAINT FK_RECIPE_EQUIP FOREIGN KEY (EQUIP_ID)
    REFERENCES dbo.TB_EQUIPMENT(EQUIP_ID),
  CONSTRAINT UQ_RECIPE_CONDITION UNIQUE (EQUIP_ID, FACTOR_ID, FACTOR_VALUE),
  CONSTRAINT CK_RECIPE_USE_YN CHECK (USE_YN IN ('Y','N'))
);

CREATE TABLE dbo.TB_RMS_RECIPE_PARAMETER (
  RECIPE_ID       NVARCHAR(50)  NOT NULL,
  PARAMETER_ID    NVARCHAR(50)  NOT NULL,
  PARAMETER_VALUE NVARCHAR(500) NOT NULL,
  CREATED_AT      DATETIME2(3)  NOT NULL DEFAULT SYSDATETIME(),
  UPDATED_AT      DATETIME2(3)  NULL,
  CONSTRAINT PK_RECIPE_PARAMETER
    PRIMARY KEY (RECIPE_ID, PARAMETER_ID),
  CONSTRAINT FK_PARAMETER_RECIPE FOREIGN KEY (RECIPE_ID)
    REFERENCES dbo.TB_RMS_RECIPE(RECIPE_ID) ON DELETE CASCADE
);
GO

-- EF Core Database First
-- Scaffold-DbContext 실행 후 Entity 클래스와 DbContext를 생성한다.
