/* RMS 기준정보 관리 — 03. 시연용 샘플 데이터 (선택)
   Kafka 과제 요청 XML 예제(EQP_001 / MODEL / A100 → RECIPE_001, TEMP_LIMIT 85, PRESS_LIMIT 3.2)에 맞춘 값 */
USE YsRmsDB;
GO
IF NOT EXISTS (SELECT 1 FROM dbo.TB_EQUIPMENT WHERE EQUIP_ID = N'EQP_001')
BEGIN
    INSERT INTO dbo.TB_EQUIPMENT (EQUIP_ID, EQUIP_NAME) VALUES (N'EQP_001', N'설비 1호기'), (N'EQP_002', N'설비 2호기');
    INSERT INTO dbo.TB_RMS_RECIPE (RECIPE_ID, EQUIP_ID, FACTOR_ID, FACTOR_VALUE)
    VALUES (N'RECIPE_001', N'EQP_001', N'MODEL', N'A100'),
           (N'RECIPE_002', N'EQP_001', N'MODEL', N'B200'),
           (N'RECIPE_003', N'EQP_002', N'MODEL', N'A100');
    INSERT INTO dbo.TB_RMS_RECIPE_PARAMETER (RECIPE_ID, PARAMETER_ID, PARAMETER_VALUE)
    VALUES (N'RECIPE_001', N'TEMP_LIMIT', N'85'), (N'RECIPE_001', N'PRESS_LIMIT', N'3.2'),
           (N'RECIPE_002', N'TEMP_LIMIT', N'90'), (N'RECIPE_002', N'PRESS_LIMIT', N'3.5'),
           (N'RECIPE_003', N'TEMP_LIMIT', N'80');
END
GO
